In [1]:
!pip install prophet

Requirement already satisfied: prophet in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (1.1.5)
Requirement already satisfied: cmdstanpy>=1.0.4 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from prophet) (1.2.0)
Requirement already satisfied: numpy>=1.15.4 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from prophet) (1.24.4)
Requirement already satisfied: matplotlib>=2.0.0 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from prophet) (3.7.3)
Requirement already satisfied: pandas>=1.0.4 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from prophet) (2.0.3)
Requirement already satisfied: holidays>=0.25 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from prophet) (0.35)
Requirement already satisfied: tqdm>=4.36.1 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from prophet) (4.66.1)
Requirement already satisfied: importlib-resources in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from prophet) (6.1.0)
Requirement already satisfied: stanio~=0.3.0 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from cmdstanpy>=1.0.4->prophet) (0.3.0)
Requirement already satisfied: python-dateutil in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from holidays>=0.25->prophet) (2.8.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from matplotlib>=2.0.0->prophet) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from matplotlib>=2.0.0->prophet) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from matplotlib>=2.0.0->prophet) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from matplotlib>=2.0.0->prophet) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from matplotlib>=2.0.0->prophet) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from matplotlib>=2.0.0->prophet) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from matplotlib>=2.0.0->prophet) (3.1.1)
Requirement already satisfied: zipp>=3.1.0 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from importlib-resources->prophet) (3.17.0)
Requirement already satisfied: pytz>=2020.1 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from pandas>=1.0.4->prophet) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from pandas>=1.0.4->prophet) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/varsharohidekar/miniforge3/envs/kaggle/lib/python3.8/site-packages (from python-dateutil->holidays>=0.25->prophet) (1.16.0)

In [2]:
from prophet import Prophet
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Importing plotly failed. Interactive plots will not work.

In [3]:
# Load the train.csv trainset
train = pd.read_csv('train.csv')

In [4]:
# Load the train.csv trainset
train['Date'] = pd.to_datetime(train['Date'])
train = train.set_index(['Date'])

In [5]:
import pandas as pd

# Define the number of weeks to lag
lag_weeks = 2  # Adjust this as needed

# Create lagged values for 'Open' and 'Volume'
train['Open_lagged'] = train['Open'].shift(lag_weeks)
train['Volume_lagged'] = train['Volume'].shift(lag_weeks)

# Drop rows with NaN values (resulting from the shift)
train = train.dropna()

In [6]:
train

,id,Open,Close,Volume,Strategy,Open_lagged,Volume_lagged
Date,,,,,,,
2015-06-15,2,47.701942,71.140831,250670900,Buy,66.208486,298506300.0
2015-06-22,3,54.754816,72.881344,223614300,Hold,64.116235,227974800.0
2015-06-29,4,48.031899,66.284718,406814900,Buy,47.701942,250670900.0
2015-07-06,5,51.374399,58.494017,590857400,Buy,54.754816,223614300.0
2015-07-13,6,45.851376,60.269347,693570200,Buy,48.031899,406814900.0
...,...,...,...,...,...,...,...
2021-01-25,295,81.284821,83.373498,117281600,Sell,79.840215,152163700.0
2021-02-01,296,71.970249,85.294903,177655800,Sell,80.663736,127248000.0
2021-02-08,297,71.784627,83.266453,146003500,Hold,81.284821,117281600.0
2021-02-15,298,69.372333,81.026827,167762500,Hold,71.970249,177655800.0
2021-02-22,299,69.618620,78.672007,332979200,Hold,71.784627,146003500.0

In [7]:
train

,id,Open,Close,Volume,Strategy,Open_lagged,Volume_lagged
Date,,,,,,,
2015-06-15,2,47.701942,71.140831,250670900,Buy,66.208486,298506300.0
2015-06-22,3,54.754816,72.881344,223614300,Hold,64.116235,227974800.0
2015-06-29,4,48.031899,66.284718,406814900,Buy,47.701942,250670900.0
2015-07-06,5,51.374399,58.494017,590857400,Buy,54.754816,223614300.0
2015-07-13,6,45.851376,60.269347,693570200,Buy,48.031899,406814900.0
...,...,...,...,...,...,...,...
2021-01-25,295,81.284821,83.373498,117281600,Sell,79.840215,152163700.0
2021-02-01,296,71.970249,85.294903,177655800,Sell,80.663736,127248000.0
2021-02-08,297,71.784627,83.266453,146003500,Hold,81.284821,117281600.0
2021-02-15,298,69.372333,81.026827,167762500,Hold,71.970249,177655800.0
2021-02-22,299,69.618620,78.672007,332979200,Hold,71.784627,146003500.0

In [8]:
train=train.drop(columns=["id"])

In [9]:
train

,Open,Close,Volume,Strategy,Open_lagged,Volume_lagged
Date,,,,,,
2015-06-15,47.701942,71.140831,250670900,Buy,66.208486,298506300.0
2015-06-22,54.754816,72.881344,223614300,Hold,64.116235,227974800.0
2015-06-29,48.031899,66.284718,406814900,Buy,47.701942,250670900.0
2015-07-06,51.374399,58.494017,590857400,Buy,54.754816,223614300.0
2015-07-13,45.851376,60.269347,693570200,Buy,48.031899,406814900.0
...,...,...,...,...,...,...
2021-01-25,81.284821,83.373498,117281600,Sell,79.840215,152163700.0
2021-02-01,71.970249,85.294903,177655800,Sell,80.663736,127248000.0
2021-02-08,71.784627,83.266453,146003500,Hold,81.284821,117281600.0
2021-02-15,69.372333,81.026827,167762500,Hold,71.970249,177655800.0
2021-02-22,69.618620,78.672007,332979200,Hold,71.784627,146003500.0

In [10]:
train.isna().sum()

Open             0
Close            0
Volume           0
Strategy         0
Open_lagged      0
Volume_lagged    0
dtype: int64

In [11]:
df = pd.read_csv("train.csv")
df.head()

   id        Date       Open      Close     Volume Strategy
0   0  2015-06-01  66.208486  75.609978  298506300     Hold
1   1  2015-06-08  64.116235  74.443331  227974800     Hold
2   2  2015-06-15  47.701942  71.140831  250670900      Buy
3   3  2015-06-22  54.754816  72.881344  223614300     Hold
4   4  2015-06-29  48.031899  66.284718  406814900      Buy

In [12]:
window_size = 5
df['SMA'] = df['Close'].rolling(window=window_size).mean()
# Calculate the Exponential Moving Average (EMA)
df['EMA'] = df['Close'].ewm(span=window_size, adjust=False).mean()

In [13]:
df

,id,Date,Open,Close,Volume,Strategy,SMA,EMA
0,0,2015-06-01,66.208486,75.609978,298506300,Hold,NaN,75.609978
1,1,2015-06-08,64.116235,74.443331,227974800,Hold,NaN,75.221096
2,2,2015-06-15,47.701942,71.140831,250670900,Buy,NaN,73.861008
3,3,2015-06-22,54.754816,72.881344,223614300,Hold,NaN,73.534453
4,4,2015-06-29,48.031899,66.284718,406814900,Buy,72.072040,71.117875
...,...,...,...,...,...,...,...,...
295,295,2021-01-25,81.284821,83.373498,117281600,Sell,83.382411,83.175676
296,296,2021-02-01,71.970249,85.294903,177655800,Sell,83.524705,83.882085
297,297,2021-02-08,71.784627,83.266453,146003500,Hold,84.029800,83.676874
298,298,2021-02-15,69.372333,81.026827,167762500,Hold,83.370286,82.793525
299,299,2021-02-22,69.618620,78.672007,332979200,Hold,82.326737,81.419686

In [14]:
df = df.drop(columns=["id"])

In [15]:
df

,Date,Open,Close,Volume,Strategy,SMA,EMA
0,2015-06-01,66.208486,75.609978,298506300,Hold,NaN,75.609978
1,2015-06-08,64.116235,74.443331,227974800,Hold,NaN,75.221096
2,2015-06-15,47.701942,71.140831,250670900,Buy,NaN,73.861008
3,2015-06-22,54.754816,72.881344,223614300,Hold,NaN,73.534453
4,2015-06-29,48.031899,66.284718,406814900,Buy,72.072040,71.117875
...,...,...,...,...,...,...,...
295,2021-01-25,81.284821,83.373498,117281600,Sell,83.382411,83.175676
296,2021-02-01,71.970249,85.294903,177655800,Sell,83.524705,83.882085
297,2021-02-08,71.784627,83.266453,146003500,Hold,84.029800,83.676874
298,2021-02-15,69.372333,81.026827,167762500,Hold,83.370286,82.793525
299,2021-02-22,69.618620,78.672007,332979200,Hold,82.326737,81.419686

In [16]:
import pandas as pd

lag_weeks_2 = 2
lag_weeks_1 = 1 
df['Open_lagged2'] = df['Open'].shift(lag_weeks_2)
df['Volume_lagged2'] = df['Volume'].shift(lag_weeks_2)

df['Open_lagged1'] = df['Open'].shift(lag_weeks_1)
df['Volume_lagged1'] = df['Volume'].shift(lag_weeks_1)
df = df.dropna()

In [18]:
df.dropna(inplace=True)

/var/folders/fk/wrg1vggd4xs6syzhgcg1dkqh0000gn/T/ipykernel_34818/1379821321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [20]:
df.isna().sum()

Date              0
Open              0
Close             0
Volume            0
Strategy          0
SMA               0
EMA               0
Open_lagged2      0
Volume_lagged2    0
Open_lagged1      0
Volume_lagged1    0
dtype: int64

In [23]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

# Assuming you have a dfFrame 't1' with features and a target variable
X = df[['Open', 'Volume', 'Open_lagged1',"Volume_lagged1","SMA","EMA","Open_lagged2","Volume_lagged2"]] # Features (excluding 'Close')
y = df['Close']  # Target variable (assuming it's continuous)

# Create a Random Forest regression model
model = RandomForestRegressor(n_estimators=100)
model.fit(X, y)

# Get feature importances
feature_importances = model.feature_importances_

# Create a dfFrame to store feature names and their importances
feature_importance_df = pd.DataFrame({'Feature': X.columns, 'Importance': feature_importances})

# Sort the features by importance in descending order
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# Select the top 'k' features
k = min(4, len(X.columns))  # Select a maximum of 3 features or fewer
selected_features = feature_importance_df['Feature'][:k]

# Print the selected features
print("Selected Features:")
print(selected_features)

Selected Features:
5             EMA
6    Open_lagged2
4             SMA
2    Open_lagged1
Name: Feature, dtype: object

In [ ]:
t1

In [ ]:

# Rename columns to fit Prophet's requirements
train = train.rename(columns={'Date': 'ds', 'Close': 'y', 'Open': 'open0',"Open_lagged":"open2","Close_SMA":'Close_SMA'})

# Create and fit the Prophet model with Open and Volume as regressors
model = Prophet()
model.add_regressor('open0')
model.add_regressor('volume0')
model.add_regressor("open2")
model.add_regressor("volume2")

model.fit(train)

In [ ]:
test = pd.read_csv('test.csv')

In [ ]:
train=pd.read_csv("train.csv")
test = pd.concat([train[["id","Date","Open","Volume"]].tail(lag_weeks),test[["id","Date","Open","Volume"]]])
test

# Define the number of weeks to lag
lag_weeks = 2  # Adjust this as needed

# Create lagged values for 'Open' and 'Volume'
test['Open_lagged'] = test['Open'].shift(lag_weeks)
test['Volume_lagged'] = test['Volume'].shift(lag_weeks)

# Drop rows with NaN values (resulting from the shift)
test = test.dropna()

In [ ]:
test

In [ ]:
# Load the test.csv trainset

test = test.rename(columns={'Date': 'ds', 'Open': 'open0', 'Volume': 'volume0',"Open_lagged":"open2","Volume_lagged":"volume2"})

# Make predictions for the test train
forecast = model.predict(test)

In [ ]:
# Extract the Close price forecasts from the predictions
close_forecast = forecast[['ds', 'yhat']]
close_forecast.index=[i for i in range(300,400)]
# Print the Close price forecasts
print("Close Price Forecast:")
print(close_forecast)

In [ ]:
plt.figure(figsize=(10,6))
train.Close.plot()
close_forecast["yhat"].plot()

# TASK2

In [ ]:
train = pd.read_csv("train.csv", index_col=1, parse_dates=True)
train=train.drop("id",axis=1)
test = pd.read_csv("test.csv", index_col=1, parse_dates=True)
test=test.drop("id",axis=1)
test["Close"]=close_forecast["yhat"].values

In [ ]:
t1=train
t1_dummies = pd.get_dummies(t1,columns=["Strategy"]).astype(float)
X = t1_dummies[["Close","Open","Volume"]]
Y = t1_dummies[["Strategy_Buy","Strategy_Hold","Strategy_Sell"]]
x_pred = test[["Close","Open","Volume"]]

In [ ]:
mapping={"Buy":0,"Hold":1,"Sell":2}
Y = train.Strategy.map(mapping)
Y

In [ ]:
X_train = X[["Close","Open","Volume"]][:240]
# y_train = Y[["Strategy_Buy","Strategy_Hold","Strategy_Sell"]][:240]
y_train=Y[:240]
X_test = X[["Close","Open","Volume"]][240:]
# y_test = Y[["Strategy_Buy","Strategy_Hold","Strategy_Sell"]][240:]
y_test=Y[240:]

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

# Define the parameter grid for hyperparameter tuning
params = {
    'C': [0.001, 0.01, 0.1, 1, 10],
    'penalty': ['l2'],
    'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
    'max_iter': [100, 200, 300]
}

best_score = 0  # Initialize best_score
best_params = {}  # Initialize best_params

# Iterate through the parameter grid
for C in params['C']:
    for penalty in params['penalty']:
        for solver in params['solver']:
            for max_iter in params['max_iter']:
                # Create a Logistic Regression model with the current hyperparameters
                clf = LogisticRegression(
                    C=C,
                    penalty=penalty,
                    solver=solver,
                    max_iter=max_iter,
                    random_state=42,
                    multi_class='ovr'  # 'ovr' for one-vs-rest (for multi-class classification)
                )

                # Train the model on the training train
                clf.fit(X_train, y_train)

                # Make predictions on the test train
                y_pred = clf.predict(X_test)

                # Calculate the accuracy score
                accuracy = accuracy_score(y_test, y_pred)

                # Check if the current model has a higher accuracy score
                if accuracy > best_score:
                    best_score = accuracy
                    best_params = {
                        'C': C,
                        'penalty': penalty,
                        'solver': solver,
                        'max_iter': max_iter
                    }

# Print the best accuracy score and corresponding hyperparameters
print("Best Accuracy Score:", best_score)
print("Best Hyperparameters:", best_params)

In [ ]:
x_pred

In [ ]:
from sklearn.tree import DecisionTreeClassifier

# Initialize and train a decision tree classifier
classifier = DecisionTreeClassifier(max_depth=20,
                                    min_samples_split=2,  # Minimum samples required to split an internal node
                                    min_samples_leaf=1,
                                    criterion='gini',
                                    random_state=42)
classifier.fit(X,Y)
y_pred = classifier.predict(x_pred)
ans=[]
for i in range(len(y_pred)):
    if y_pred[i][0]==1:
        ans.append("Buy")
    elif y_pred[i][1]==1:
        ans.append("Hold")
    else:
        ans.append("Sell")
ans.count("Buy"), ans.count("Hold"), ans.count("Sell")

In [ ]:
submission = pd.trainFrame()
submission["Date"] = test.index
submission["Close"] = test["Close"].values
submission["Strategy"] = ans
submission.index.name="id"
submission.head()

In [ ]:
submission.to_csv('prophet.csv', index=True)

# METHOD 2

In [ ]:
zz

In [ ]:
close_forecast.yhat=np.exp(close_forecast.yhat)
close_forecast

In [ ]:
train_train.y=np.exp(train_train.y)

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(20,6))
train_train.y.plot()
close_forecast["yhat"].plot()

In [ ]:
train = pd.read_csv("train.csv", index_col=1, parse_dates=True)
train=train.drop("id",axis=1)
test = pd.read_csv("test.csv", index_col=1, parse_dates=True)
test=test.drop("id",axis=1)
test["Close"]=close_forecast["yhat"].values

In [ ]:
t1=train
t1_dummies = pd.get_dummies(t1,columns=["Strategy"]).astype(float)
X = t1_dummies[["Close","Open","Volume"]]
Y = t1_dummies[["Strategy_Buy","Strategy_Hold","Strategy_Sell"]]
x_pred = test[["Close","Open","Volume"]]

In [ ]:
from sklearn.tree import DecisionTreeClassifier

# Initialize and train a decision tree classifier
classifier = DecisionTreeClassifier(max_depth=10,
                                    min_samples_split=2,  # Minimum samples required to split an internal node
                                    min_samples_leaf=1,
                                    criterion='entropy',
                                    random_state=42)
classifier.fit(X,Y)
y_pred = classifier.predict(x_pred)
ans=[]
for i in range(len(y_pred)):
    if y_pred[i][0]==1:
        ans.append("Buy")
    elif y_pred[i][1]==1:
        ans.append("Hold")
    else:
        ans.append("Sell")
ans.count("Buy"), ans.count("Hold"), ans.count("Sell")

In [ ]:
submission = pd.trainFrame()
submission["Date"] = test.index
submission["Close"] = test["Close"].values
submission["Strategy"] = ans
submission.index.name="id"
submission.head()

In [ ]:
submission.to_csv('prophet.csv', index=True)